// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhVwz6eZ4sVXR9J-y82J9iCtxFZH2VtLw',
    appId: '1:906715819091:web:f4edb89ca3ddf08befeaa6',
    messagingSenderId: '906715819091',
    projectId: 'quizfypp',
    authDomain: 'quizfypp.firebaseapp.com',
    databaseURL: 'https://quizfypp-default-rtdb.firebaseio.com',
    storageBucket: 'quizfypp.appspot.com',
    measurementId: 'G-TRSZTEQMRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWXeLTVxjoypYhgbAmNQTRxt258xcuYF0',
    appId: '1:906715819091:android:1d3b8d609e49484defeaa6',
    messagingSenderId: '906715819091',
    projectId: 'quizfypp',
    databaseURL: 'https://quizfypp-default-rtdb.firebaseio.com',
    storageBucket: 'quizfypp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnhw0_VRqLAMcLR1lu_XtKZPOCK15Fn0',
    appId: '1:906715819091:ios:294cb08d86d2da7cefeaa6',
    messagingSenderId: '906715819091',
    projectId: 'quizfypp',
    databaseURL: 'https://quizfypp-default-rtdb.firebaseio.com',
    storageBucket: 'quizfypp.appspot.com',
    androidClientId: '906715819091-fi90efr3fa8d97atas8o5rsl50bh5lcj.apps.googleusercontent.com',
    iosClientId: '906715819091-ceq4dpn1njqf7ltnu275qpmuplj871fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATnhw0_VRqLAMcLR1lu_XtKZPOCK15Fn0',
    appId: '1:906715819091:ios:7795ec45383575e3efeaa6',
    messagingSenderId: '906715819091',
    projectId: 'quizfypp',
    databaseURL: 'https://quizfypp-default-rtdb.firebaseio.com',
    storageBucket: 'quizfypp.appspot.com',
    androidClientId: '906715819091-fi90efr3fa8d97atas8o5rsl50bh5lcj.apps.googleusercontent.com',
    iosClientId: '906715819091-gsh72318chuce5t0lga302m4es2de9ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz.RunnerTests',
  );
}
